import * as fs from 'fs';
import { getEnvPath } from './paths';

export interface WizardConfig {
  // AI Providers
  anthropic_api_key?: string;
  openai_api_key?: string;
  google_ai_key?: string;
  xai_api_key?: string;
  // Market
  market_timezone: string;
  // Budget
  monthly_budget_limit: number;
  daily_budget_warning: number;
  // Data providers
  polygon_api_key?: string;
  alpha_vantage_key?: string;
  finnhub_api_key?: string;
  twelve_data_key?: string;
  // Agent framework
  default_agent_framework: string;
}

/**
 * Write a .env file from wizard configuration.
 */
export function writeEnvFile(config: WizardConfig): void {
  const envPath = getEnvPath();
  const lines: string[] = [
    '# StockPulse AI - Generated by Setup Wizard',
    `# Created: ${new Date().toISOString()}`,
    '',
    '# AI Providers',
    `ANTHROPIC_API_KEY=${config.anthropic_api_key || ''}`,
    `OPENAI_API_KEY=${config.openai_api_key || ''}`,
    `GOOGLE_AI_KEY=${config.google_ai_key || ''}`,
    `XAI_API_KEY=${config.xai_api_key || ''}`,
    '',
    '# Market',
    `MARKET_TIMEZONE=${config.market_timezone}`,
    '',
    '# Budget',
    `MONTHLY_BUDGET_LIMIT=${config.monthly_budget_limit}`,
    `DAILY_BUDGET_WARNING=${config.daily_budget_warning}`,
    '',
    '# Data Providers (optional)',
    `POLYGON_API_KEY=${config.polygon_api_key || ''}`,
    `ALPHA_VANTAGE_KEY=${config.alpha_vantage_key || ''}`,
    `FINNHUB_API_KEY=${config.finnhub_api_key || ''}`,
    `TWELVE_DATA_KEY=${config.twelve_data_key || ''}`,
    '',
    '# Agent Framework',
    `DEFAULT_AGENT_FRAMEWORK=${config.default_agent_framework}`,
    '',
    '# App (fixed for desktop)',
    'FLASK_PORT=5000',
    'FLASK_DEBUG=false',
    'LOG_LEVEL=INFO',
    '',
  ];

  fs.writeFileSync(envPath, lines.join('\n'), 'utf-8');
}

/**
 * Parse a .env file into a key-value record.
 */
export function parseEnvFile(envPath: string): Record<string, string> {
  const vars: Record<string, string> = {};
  if (!fs.existsSync(envPath)) return vars;
  const content = fs.readFileSync(envPath, 'utf-8');
  for (const line of content.split('\n')) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) continue;
    const eqIndex = trimmed.indexOf('=');
    if (eqIndex > 0) {
      vars[trimmed.substring(0, eqIndex)] = trimmed.substring(eqIndex + 1);
    }
  }
  return vars;
}
